---
backend:
  name: github
  repo: ssarault/hugo-restaurant-tutorial
  branch: master
  
media_folder: "src/img/gallery"
  
collections:
    -name: food
	label: "Food Item"
	folder: "site/content/food"
	create: true
	fields:
	  - {label: "Name of Item", name: "title", widget: "string"}
	  - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "dinner"]}
	  - {label: "Ingredients/Description", name: "description", widget: "text"}
	  - {label: "Type of Food", name: "type", widget: "string", default: "raw bar"}
	  - {label: "Price", name: "price", widget: "string"}